### ISSUE TITLE
tvdel has wrong delegate method. Think you wanted didSelect NOT didDeselect

### ISSUE THREAD

**Issue by bytor99999** [Abizern/xcode-snippets#2]
didDeselectRowAtIndexPath in the snippet should be

didSelectRowAtIndexPath

Very common mistake with auto-complete. I do it all the time too.

Mark

**Comment by Abizern** [comment]
That is mortifying :(. Thanks for pointing it out.

**Comment by bytor99999** [comment]
No Worries. Code snippets are great. I have some really big ones, that I know have mistakes in them. But luckily, I am the only one using them, so I know what they are and how to fix those. ;)

Thanks again for your project, you are helping a LOT of us out with it.

Mark Spritzler
